//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica01.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Practica01.Idiomas.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Árabe.
        /// </summary>
        internal static string arab {
            get {
                return ResourceManager.GetString("arab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chino.
        /// </summary>
        internal static string chinese {
            get {
                return ResourceManager.GetString("chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar ranking.
        /// </summary>
        internal static string clearRanking {
            get {
                return ResourceManager.GetString("clearRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creador: Oscar Antelo.
        /// </summary>
        internal static string creator {
            get {
                return ResourceManager.GetString("creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida en curso.
        /// </summary>
        internal static string currentGame {
            get {
                return ResourceManager.GetString("currentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad.
        /// </summary>
        internal static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facil.
        /// </summary>
        internal static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad: facil.
        /// </summary>
        internal static string easyMode {
            get {
                return ResourceManager.GetString("easyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El tiempo se ha agotado!.
        /// </summary>
        internal static string endgameDefeat {
            get {
                return ResourceManager.GetString("endgameDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje de fin de partida.
        /// </summary>
        internal static string endgameMessage {
            get {
                return ResourceManager.GetString("endgameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Has completado el juego!.
        /// </summary>
        internal static string endgameVictory {
            get {
                return ResourceManager.GetString("endgameVictory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un nivel de dificultad.
        /// </summary>
        internal static string errorDifficulty {
            get {
                return ResourceManager.GetString("errorDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje de error.
        /// </summary>
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca un nombre de usuario.
        /// </summary>
        internal static string errorUsername {
            get {
                return ResourceManager.GetString("errorUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extrema.
        /// </summary>
        internal static string extreme {
            get {
                return ResourceManager.GetString("extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad: extrema.
        /// </summary>
        internal static string extremeMode {
            get {
                return ResourceManager.GetString("extremeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentra las parejas.
        /// </summary>
        internal static string findPairs {
            get {
                return ResourceManager.GetString("findPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frances.
        /// </summary>
        internal static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificil.
        /// </summary>
        internal static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad: dificil.
        /// </summary>
        internal static string hardMode {
            get {
                return ResourceManager.GetString("hardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ● Jugador:
        ///● Dificultad:
        ///● Retardo (s):
        ///● Errores cometidos:
        ///● Puntuación:.
        /// </summary>
        internal static string infoCurrentGame {
            get {
                return ResourceManager.GetString("infoCurrentGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ● Tiempo disponible: 
        ///● Penalización/error:.
        /// </summary>
        internal static string infoMode {
            get {
                return ResourceManager.GetString("infoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ● Tiempo empleado:
        ///● Errores cometidos:
        ///● Puntuación:.
        /// </summary>
        internal static string infoSummaryGame {
            get {
                return ResourceManager.GetString("infoSummaryGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        internal static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad: media.
        /// </summary>
        internal static string mediumMode {
            get {
                return ResourceManager.GetString("mediumMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ranking.
        /// </summary>
        internal static string ranking {
            get {
                return ResourceManager.GetString("ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de recarga.
        /// </summary>
        internal static string rechargeTime {
            get {
                return ResourceManager.GetString("rechargeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar partida.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen de partida.
        /// </summary>
        internal static string summaryGame {
            get {
                return ResourceManager.GetString("summaryGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo restante.
        /// </summary>
        internal static string timeLeft {
            get {
                return ResourceManager.GetString("timeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
